Repository SU-SWS/netlify-plugin-vault-variables, pull requests merged in 2022-03, with the labels that each got.

#1 ADAPT-4355: Adding support for contextul vars, linter configuration, etc.
  .eslintrc
  .github/auto-label.json
  .github/pr-labeler.yml
  .github/pull_request_template.md
  .github/workflows/release.yml
  LICENSE
  README.md
  package-lock.json
  package.json
  src/contextualEnvVars.js
  src/index.js
  src/script.js
Labels: size/xl

#3 Release 1.0.4
  README.md
Labels: size/xs

#5 BUG: Fix dependencies.
  README.md
  package-lock.json
  package.json
Labels: size/l, patch

#6 Release 1.0.4 (#3)
  README.md
  package-lock.json
  package.json
Labels: size/l, patch
